Update encode.js to add saving functionality
CKegel/Web-SSTV pull request #6
Opened 2024-10-21 18:38 UTC by commandcontrolQ

I changed the pull request so it is linked to my fork: ignore the previous one.

Added functionality to allow users to save encoded SSTV audio as a WAV file using the MediaRecorder API.

On page load, the download button is disabled.
The MediaRecorder API records the output of the encoded waveforms and converts the audio buffer into a WAV file.
The download button only becomes clickable when the image is done encoding, and then when clicked, the audio will be downloaded to the user's computer as `sstv_{image_filename}.wav`.

2024-10-21 22:52 UTC, commandcontrolQ commented
This would also help make it easier to implement a decoder by eliminating interference (from live audio), although it would still be nice to see a live SSTV decoder.

2024-10-28 14:15 UTC, CKegel commented
I've been a little behind with my normal work - but I am to fully review this and merge (or provide feedback) by the end of the week. Sorry for the delay!

2024-10-28 15:00 UTC, commandcontrolQ commented
There are some quirks with the recorded WAV files:
1. The recorded audio does not start until after a second of playback.
2. The audio quality is low.

2024-11-12 21:29 UTC, daisseur commented
Hey @commandcontrolQ I'm implementing your code in my fork. Thanks for the contrib !

2024-11-16 05:20 UTC, CKegel requested changes
As noted, I've found the `OfflineAudioContext` API to be the better approach in my testing. If you'd like to swap over to that approach I'd be happy to merge. Additionally please adjust your request to merge into dev so I can adjust things before pushing it live.

2024-11-16 05:20 UTC, CKegel commented on encode.js
> +	recorder.ondataavailable = (e) => {
Instead of using the `MediaRecorder` API, I'd prefer if you used the `OfflineAudioContext` api.

2024-11-16 06:20 UTC, closed without merging

2024-11-16 06:20 UTC, CKegel commented
I just finished implementing this and pushed it to the site. I appreciate your contribution. Your encode WAV function helped me sanity check mine.

2024-11-16 08:33 UTC, commandcontrolQ commented
> As noted, I've found the `OfflineAudioContext` API to be the better approach in my testing. If you'd like to swap over to that approach I'd be happy to merge. Additionally please adjust your request to merge into dev so I can adjust things before pushing it live.

I am quite busy, however I am happy to change the API used in my fork. Additionally, could you specify what needs to be adjusted?